--adding sql statements in pl/sql

CREATE TABLE EMPLOYEETRAIL(
        EID INT,
        ENAME VARCHAR(20),
        ESAL NUMBER
 );
 
  INSERT INTO EMPLOYEETRAIL (EID,ENAME,ESAL)
        VALUES(101,'akash',22000);

DECLARE 
        EMP_NAME VARCHAR(20);
        SALARY INT;
        EMP_ID INT :=101;
BEGIN 
        --SELECT STATEMENT 
        SELECT ENAME INTO EMP_NAME
        FROM EMPLOYEETRAIL
        WHERE EID = EMP_ID;
        
        DBMS_OUTPUT.PUT_LINE('NAME IS ' || EMP_NAME);
        
        --INSERT STATEMENTS
        INSERT INTO EMPLOYEETRAIL (EID,ENAME,ESAL)
        VALUES(102,'VISHWA',20000);
        
        SELECT ENAME,ESAL INTO EMP_NAME ,SALARY
        FROM EMPLOYEETRAIL
        WHERE EID = 102;
        DBMS_OUTPUT.PUT_LINE('NAME IS ' || EMP_NAME || ' SALARY IS ' || SALARY );
        
        --UPDATE STATEMENTS 
        UPDATE  EMPLOYEETRAIL
        SET ESAL = ESAL +ESAL*0.1
        WHERE EID=102;
        
        SELECT ENAME,ESAL INTO EMP_NAME ,SALARY
        FROM EMPLOYEETRAIL
        WHERE EID = 102;
        DBMS_OUTPUT.PUT_LINE('NAME IS ' || EMP_NAME || ' UPDATED SALARY IS ' || SALARY);
        
        --DELETE STATEMENTS 
        DELETE FROM EMPLOYEETRAIL 
        WHERE EID=102;
        
        DBMS_OUTPUT.PUT_LINE('OPERATIONS COPMPLETED SUCCESSFULLY');
END;
